"""

This script automates the evaluation of multiple machine learning pipelines generated by TPOT (Tree-based Pipeline Optimization Tool) to find the best pipeline. 

While the earlier script (runAutoML) was about running TPOT once and exporting the best pipeline,

This script is about benchmarking many pipelines side by side (both TPOT-generated and manually).

It ensures fairness (same random_state, same dataset split) and produces a formal PDF report with metrics + plots.

The aim is to compare different ML pipelines systematically (all found via TPOT or modified versions) and document their performance in one standardized report.

Overview
--------

The scripts:

   1. Loads data from a SQLite database (``ews_data_nomiss.sqlite``).

   2. Splits into train/test using a balanced setup.

   3. Builds multiple pipelines with different combinations of preprocessing + models.

   4. Evaluates them (classification report, F1 score, learning curve, probability calibration).

   5. Saves results to a PDF report with plots and tables.

"""
import pandas as pd
import sqlite3 as db
from datetime import datetime


from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score 
from sklearn.pipeline import make_pipeline, make_union
from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier
from sklearn.feature_selection import SelectPercentile, f_classif, RFE # "recursive feature elimination" (RFE) 
from sklearn.svm import LinearSVC
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import Normalizer # Each sample (i.e. each row of the data matrix) with at least one non zero component is rescaled 
from sklearn.base import BaseEstimator, TransformerMixin, is_classifier
from sklearn.utils import check_array
from sklearn.linear_model import SGDClassifier

from sklearn.preprocessing import Binarizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import BernoulliNB

from xgboost import XGBClassifier

import numpy as np

from copy import copy # it returns a shallow copy of the object 
import io 

import matplotlib.pyplot as plt

# pip install fpdf
from fpdf import FPDF

# General Configuration
dbfn='ews_data_nomiss.sqlite'

targetVarName='crisis0'

random_state=42

sep='*'*20

baseCovariates = ['real_gdp_growth_ifs_1', 'lgdp_per_capita_wdi_1', 'defl_gdp_growth_wdi_1', 'realirate_ifs_1', 'm2_to_fereserves_wdi_1', 'domcrpriv_growth_wdi_1', 
                'ld_nfassets_to_gdp_wdi_1', 'aux1'   # dropped because the null values
                ]
    
    

rollingAdditionalCovariates = ['os1_crisis0',
       'os1_real_gdp_growth_ifs_1', 'os1_lgdp_per_capita_wdi_1',
       'os1_defl_gdp_growth_wdi_1', 'os1_realirate_ifs_1',
       'os1_m2_to_fereserves_wdi_1', 'os1_domcrpriv_growth_wdi_1',
       'os1_ld_nfassets_to_gdp_wdi_1', 'os1_aux1', 'os2_crisis0',
       'os2_real_gdp_growth_ifs_1', 'os2_lgdp_per_capita_wdi_1',
       'os2_defl_gdp_growth_wdi_1', 'os2_realirate_ifs_1',
       'os2_m2_to_fereserves_wdi_1', 'os2_domcrpriv_growth_wdi_1',
       'os2_ld_nfassets_to_gdp_wdi_1', 'os2_aux1', 'os3_crisis0',
       'os3_real_gdp_growth_ifs_1', 'os3_lgdp_per_capita_wdi_1',
       'os3_defl_gdp_growth_wdi_1', 'os3_realirate_ifs_1',
       'os3_m2_to_fereserves_wdi_1', 'os3_domcrpriv_growth_wdi_1',
       'os3_ld_nfassets_to_gdp_wdi_1', 'os3_aux1', 'os4_crisis0',
       'os4_real_gdp_growth_ifs_1', 'os4_lgdp_per_capita_wdi_1',
       'os4_defl_gdp_growth_wdi_1', 'os4_realirate_ifs_1',
       'os4_m2_to_fereserves_wdi_1', 'os4_domcrpriv_growth_wdi_1',
       'os4_ld_nfassets_to_gdp_wdi_1', 'os4_aux1',
       'crisis0_last'
    ]



def log(*var, **kvar):
    """
    **Logging utility Function**

    This function writes messages to a log file (`s02automl.log2.txt`) and 
    simultaneously prints them to the console. It is primarily used to 
    document the progress of AutoML runs and record key information about 
    parameters, configurations, and performance.

    **Workflow**
    
    - A timestamp (formatted as YYYY_MM_DD__HH_MM_SS) is prepended to every log entry.
    - Any  arguments (`*var`) are joined by commas and added to the log line.
    - Any keyword arguments (`**kvar`) are appended to the log line as "key:value" pairs,
      separated by commas and preceded by an asterisk ("*").
    - The resulting log line is written to a text file (`s02automl.log2.txt`) and printed.

    Parameters
    ----------
    
    *`var` : list
        Variable-length positional arguments. These will be stringified 
        and concatenated into the log message.
    **`kvar` : dict
        Variable-length keyword arguments. These will be formatted as 
        "key:value" pairs in the log message.
    
    """
    fn = 's02automl.log.txt'
    with open(fn,'a') as fd:
        line = datetime.now().strftime("%Y_%m_%d__%H_%M_%S")
        line+=' '
        if var is not None:
            line += ','.join([str(el) for el in var])
        #if kvar is not None:
        if len(kvar)>0:
            line+=' * '
            line+=','.join([str(k)+':'+str(v) for k,v in kvar.items()])
        line+='\n'
        fd.write(line)
        print(line)

def readDataset(
        dbfn = '',
        tableName=''
    ):
    conn = db.connect(dbfn)
    query=f'select * from {tableName}'
    df = pd.read_sql(query,conn)
    conn.close()
    return df


def geTrainTesttDataset(datasetNickName):
    """
    Generate training and testing datasets for early warning models.

    Depending on the name of the dataset, this function loads and verify the presence of 
    required target variable and covariates and splits the dataset into train and test datsets.

    Parameters
    ----------
    datasetNickName: str
       Name of the dataset configuration. Must be one of:
         * `early_warning_ml` - uses table `cr03_ml` with the base covariates + `crisis0_1` variabel.
         * `early_warning_ml_rolling_window` - uses a table `cr03_ml_rolling` with the base covariates + rolling variables( lagged values (`os1_`, `os2_`, `os3_`, `os4_`) ).

    Returns
    -------
    xTrain :  pandas.DataFrame
        Training feature set (covariates).
    xTest : pandas.DataFrame
        Testing feature set (covariates).
    yTrain : pandas.series
        Training target variable.
    yTest : pandas.series
        Testing target variable.

    Notes
    -----
    -  Drops the `index` column from the dataset if present.
    - Uses `grp` column values (`'balanced_train'` and `'balanced_test'`)
      to create train/test splits.
    - Relies on external variables: `baseCovariates`, `rollingAdditionalCovariates`,
      `targetVarName`, `dbfn`, and function `readDataset`.

    """
    assert datasetNickName in ['early_warning_ml', 'early_warning_ml_rolling_window']
    if datasetNickName == 'early_warning_ml':
        tableName='cr03_ml' 
        rolling=False 
        covariates = baseCovariates + ['crisis0_1']     
    elif datasetNickName == 'early_warning_ml_rolling_window':
        tableName='cr03_ml_rolling'
        rolling=True
        covariates = baseCovariates + rollingAdditionalCovariates

    else:
        log('Unrecognized datasetName')
        return 
    

    dfb = readDataset(
        dbfn = dbfn,
        tableName=tableName
    )

    if 'index' in dfb.columns:
        dfb.drop(columns=['index'], inplace=True)

    # Checking that target variables and covariates are available
    for col in [targetVarName]+covariates:
        assert col in dfb.columns , f'Attribute *{col}* not found'
        

    trainSelectionMask = dfb.grp=='balanced_train'
    testSelectionMask = dfb.grp=='balanced_test'

    xTrain = dfb.loc[trainSelectionMask, covariates]
    xTest = dfb.loc[testSelectionMask, covariates]

    yTrain = dfb.loc[trainSelectionMask, targetVarName]
    yTest = dfb.loc[testSelectionMask, targetVarName]

    return xTrain, xTest, yTrain, yTest

def computeLearningCurveData(pipe, xTrain, xTest, yTrain, yTest, random_state=random_state):
    """
    Compute learning curve performance data for a given estimator pipeline.

    This function evaluates model performance on larger traing samples (equal crisis
    vs. nun-crisis cases). At each sample size, the model is trained and evaluates on
     both training and test sets, producing classification metrics.

    Parameters
    ----------
    pipe : sklearn.pipeline.Pipeline or estimator
      The pipeline implementing `fit` and `predict`.
    xTrain : pandas.DataFrame
      The training feature set(covariates).
    xTest : pandas.DataFrame
      The testing feature set(covariates).
    yTrain : pandas.Series
      Training labels
    yTest : pandass.Series
      Testing labels.
    random_state : random_state
      Random seed for reproducibility when sampling the trainig samples.

    Returns
    -------
    df : pandas.DataFrame
      A dataframe containing performance metrics for different training samples.
      Variables of the dataset:
        - `Num` : number of training samples used.
        - `accuracy_train` : accuracy of the train set
        - `accuracy_test` : accuracy of the test set
        - `precision_train` : precision of the train set
        - `precision_test` : precision of the test set
        - `recall_train` : recall of the train set
        - `recall_test` : recall of the test set 
        - `f1_train` : f1 of the train set
        - `f1_test` : : f1 of the test set

    Raises
    ------
    AssertionError
        If the indices of `xTrain` and `yTrain` are not aligned.

    Notes
    -----
    - Training subsets are balanced: half positive (crisis) and half negative.
    - F1 score is computed using `average='macro'`.
        
    """
    f1weightedLi=[]
    f1unweightedLi=[]
    precisionLi=[]
    recallLi=[]

    nRecords = len (xTrain)
    sampleDimensionLi = [int(nRecords*perc/100) for perc in range(5, 105, 5)]
    performanceLi=[]

    assert (xTrain.index==yTrain.index).all()

    for sampleDimension in sampleDimensionLi:
        halfSample = int(sampleDimension/2)
        # Please, make sure that half are sampled from crisis and half are sampled from non crisis
        indLiAll = yTrain[yTrain==0].sample(halfSample, random_state=random_state).index
        indLi1 = yTrain[yTrain==1].sample(halfSample, random_state=random_state).index
        indLiAll = indLiAll.union(indLi1, sort=True)

        """print(indLiAll)
        print(xTrain.head()) 
        print(yTrain.head())
        print('halfSample', halfSample)
        print(yTrain[indLiAll])

        exit()"""

        xTrainSample = xTrain.loc[indLiAll,:]
        yTrainSample = yTrain[indLiAll]

        di={}
        pipe.fit(xTrainSample, yTrainSample)

        yPredTest = pipe.predict(xTest)
        yPredTrain = pipe.predict(xTrainSample)

        di['Num']=halfSample*2

        di['accuracy_test']=accuracy_score(yTest, yPredTest)
        di['accuracy_train']=accuracy_score(yTrainSample, yPredTrain)
        
        di['precision_test']=precision_score(yTest, yPredTest)
        di['precision_train']=precision_score(yTrainSample, yPredTrain)
        
        di['recall_test']=recall_score(yTest, yPredTest)
        di['recall_train']=recall_score(yTrainSample, yPredTrain)
        
        di['f1_test']=f1_score(yTest, yPredTest, average='macro')
        di['f1_train']=f1_score(yTrainSample, yPredTrain, average='macro')
        

        performanceLi.append(
            di
        )

    df = pd.DataFrame(performanceLi)
    return df

def createLearingCurvePlot(lcDF): # Learning Curve DataFrame
    """ 
    Creates a F1 score learning curve plot from performance dataframe.

    The plot shows the F1 score os training and testing sets.

    Parameters
    ----------
    lcDF : pandas.Dataframe
      Dataframe produced by `computeLearningCurveData` function.

    Returns
    -------
    The PNG image of the learning curve.

    """
    x1 = lcDF.loc[:, 'Num'].values

    f1Train = lcDF.loc[:, 'f1_train'].values

    f1Test = lcDF.loc[:, 'f1_test'].values

    # Create a figure and plot the lines
    fig, ax = plt.subplots(figsize=(8, 6))
    ax.plot(x1, f1Train, color='blue', label='F1 Train')
    ax.plot(x1, f1Test, color='red', label='F1 Test')

    # Add title and labels
    ax.set_title('F1 Scores on samples')
    ax.set_xlabel('Sample Dimension')
    ax.set_ylabel('F1')
    ax.legend()
    ax.grid(True)

    # Save the figure to a memory buffer
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    buf.seek(0)  # Rewind buffer to start

    # Optional: if you want to use this buffer (e.g., return from API)
    # image_bytes = buf.getvalue()

    # Close the figure to free memory
    plt.close(fig)

    # Now `buf` contains the PNG image of the plot in memory
   
    #You can pass buf.getvalue() to APIs, write it to a file, or encode it (e.g., Base64) if needed.
    
    return buf











def evaluatePipeline(
        pipe, 
        datasetNickName,
    ):
    """
    Train, evaluate, and log results of a machine learning pipeline on a dataset.

    This function loads the dataset, fits the given pipeline, computes
    evaluation metrics, generates data for learning and ROC curves, logs
    the outputs, and produces a learning curve plot as an in-memory buffer.

    Parameters
    ----------
    pipe : sklearn.pipeline.Pipeline or estimator
      The estimator or pipeline implementing `fit` and `predict`. 
    datasetNickName : str
      Identifier for the dataset to load using `geTrainTesttDataset`.
 
    Returns
    -------
    rep : str
        Textual classification report from ``sklearn.metrics.classification_report``.
    f1Macro : float
        Macro-averaged F1 score on the test set.
    figBuffer : io.BytesIO
        A memory buffer containing the PNG image of the learning curve.

    Notes
    -----
    - Logs multiple intermediate results: classification report, learning curve
      data, and ROC curve data.
    - Uses :func:`computeLearningCurveData` for learning curves and
      :func:`computePredictProba` for probability-based evaluation.
    - The function assumes that ``geTrainTesttDataset`` and ``log`` are defined
      elsewhere in the codebase.
    
    """
    xTrain, xTest, yTrain, yTest = geTrainTesttDataset(datasetNickName)

    
    pipe.fit(xTrain, yTrain)
    yPred = pipe.predict(xTest)
    rep = classification_report(yTest, yPred)

    f1Macro = f1_score(yTest, yPred, average='macro')
    
    log(f'Dataset  {datasetNickName}')
    log(pipe)
    log('Classification report\n',rep)
    log('Data for Learning Curves, computed on both train and test set')
    lcDF = computeLearningCurveData(pipe, xTrain, xTest, yTrain, yTest, random_state=random_state)
    log('\n'+lcDF.to_csv(index=False))
    log('Data for Roc Curve computed on the test set')
    ppDF = computePredictProba(pipe, xTrain, xTest, yTrain, yTest, random_state=random_state)
    log('\n'+ppDF.to_csv(index=False))
    log(sep)

    figBuffer = createLearingCurvePlot(lcDF)
    return rep, f1Macro, figBuffer

# This are functions provided by tpot.
# The code was copied and pasted here to avoid importing 
# the whole tpot library

# from tpot.builtins import StackingEstimator

# It works only during transform. It horizontally stacks a classifier predict() or predict_proba() to the input features 
class StackingEstimator(BaseEstimator, TransformerMixin):
    """Meta-transformer for adding predictions and/or class probabilities as synthetic features.

    Parameters
    ----------
    estimator : object
        The base estimator from which the transformer is built.
    """

    def __init__(self, estimator):
        """Create a StackingEstimator object.

        Parameters
        ----------
        estimator: object with fit, predict, and predict_proba methods.
            The estimator to generate synthetic features from.
        """
        self.estimator = estimator

    def fit(self, X, y=None, **fit_params):
        """Fit the StackingEstimator meta-transformer.

        Parameters
        ----------
        X: array-like of shape (n_samples, n_features)
            The training input samples.
        y: array-like, shape (n_samples,)
            The target values (integers that correspond to classes in classification, real numbers in regression).
        fit_params:
            Other estimator-specific parameters.

        Returns
        -------
        self: object
            Returns a copy of the estimator
        """
        self.estimator.fit(X, y, **fit_params)
        return self

    def transform(self, X):
        """Transform data by adding two synthetic features.

        Parameters
        ----------
        X: numpy ndarray of shape (n_samples, n_components)
            New data to transform.

        Returns
        -------
        X_transformed: array-like 
           Feature matrix with additional synthetic features:
             - predicted class labels
             - predicted class probabilities (if available)
        """
        X = check_array(X)
        X_transformed = np.copy(X)

        # add class probabilities as a synthetic feature
        if is_classifier(self.estimator) and hasattr(self.estimator, 'predict_proba'):
            y_pred_proba = self.estimator.predict_proba(X)
            # check all values that should be not infinity or not NAN
            if np.all(np.isfinite(y_pred_proba)):
                X_transformed = np.hstack((y_pred_proba, X))

        # add class prediction as a synthetic feature
        X_transformed = np.hstack(
            (np.reshape(self.estimator.predict(X), (-1, 1)), X_transformed))
        return X_transformed
    

# The same as above for

# from tpot.export_utils import set_param_recursive

def set_param_recursive(pipeline_steps, parameter, value):
    """Recursively iterate through all objects in the pipeline and set a given parameter.

    Parameters
    ----------
    pipeline_steps: array-like
        List of (str, obj) tuples from a scikit-learn pipeline or related object
    parameter: str
        The parameter to assign a value for in each pipeline object
    value: any
        The value to assign the parameter to in each pipeline object
    Returns
    -------
    None

    """
    for (_, obj) in pipeline_steps:
        recursive_attrs = ["steps", "transformer_list", "estimators"]
        for attr in recursive_attrs:
            if hasattr(obj, attr):
                set_param_recursive(getattr(obj, attr), parameter, value)
        if hasattr(obj, "estimator"):  # nested estimator
            est = getattr(obj, "estimator")
            if hasattr(est, parameter):
                setattr(est, parameter, value)
        if hasattr(obj, parameter):
            setattr(obj, parameter, value)

def computePredictProba(pipe, xTrain, xTest, yTrain, yTest, random_state=random_state):
    """
    Fit a pipeline and compute predicted probabilities on the test set.

    This function checks whether the provided pipeline implements
    ``predict_proba``. If so, the model is fitted on the training set,
    class probabilities are computed on the test set, and the results
    are returned in a DataFrame. If the pipeline does not support
    ``predict_proba``, an empty DataFrame with the expected columns is
    returned instead.

    Parameters
    ----------
    pipe : sklearn.pipeline.Pipeline or estimator
        A scikit-learn compatible pipeline or estimator.
    xTrain : pandas.DataFrame
        Training feature set.
    xTest : pandas.DataFrame
        Test feature set.
    yTrain : pandas.Series or array-like
        Training target values.
    yTest : pandas.Series or array-like
        Test target values.
    random_state : int, default=random_state
        Seed for reproducibility when fitting the estimator.

    Returns
    -------
    df : pandas.DataFrame
        DataFrame containing:
        - ``yTest`` : True labels from the test set
        - ``yPredProba_0`` : Predicted probability for class 0
        - ``yPredProba_1`` : Predicted probability for class 1

        If ``predict_proba`` is not available, the DataFrame will be
        empty but still include the expected columns.

    Notes
    -----
    - Calls ``pipe.fit`` internally before computing probabilities.
    - Intended for binary classification problems where two probability
      columns are returned.
    """
    if hasattr(pipe, 'predict_proba'):
        pipe.fit(xTrain, yTrain)
        yPredProba = pipe.predict_proba(xTest)
        df = pd.DataFrame({'yTest':yTest, 'yPredProba_0':yPredProba[:,0], 'yPredProba_1':yPredProba[:,1] })
    else:
        log(pipe, 'has no method predict_proba()')
        df = pd.DataFrame({'yTest':[], 'yPredProba_0':[], 'yPredProba_1':[]})
    
    return df
    

def evaluateSeveralPipelines(
        random_state=random_state,     
    ):
    """
    Build, evaluate, and summarize multiple machine learning pipelines.

    This function constructs a set of predefined pipelines using
    scikit-learn, XGBoost, and custom stacking estimators. Each pipeline
    is trained and evaluated on either the ``early_warning_ml`` or
    ``early_warning_ml_rolling_window`` datasets, depending on its
    configuration. The evaluation includes a classification report,
    F1-macro score, and a learning curve plot. Results are aggregated
    and exported into a PDF file.

    Parameters
    ----------
    random_state : int, default=random_state
        Seed for reproducibility, applied recursively to all estimators
        within the pipelines.

    Returns
    -------
    None
        Saves a PDF file named ``separate_pipes_evaluation_result.pdf``
        in the working directory. The PDF includes:
        - One page per pipeline, with dataset information,
          classification report, and learning curve plot.
        - A summary table with F1-macro scores for all pipelines.

    Notes
    -----
    - Internally, this function uses :func:`evaluatePipeline` to train and
      evaluate each pipeline.
    - Intermediate plots are temporarily saved to disk before being
      embedded into the PDF via FPDF.
    - The pipelines are based on models produced or inspired by TPOT
      and manually tuned variants.
    """
    p1=make_pipeline(
        make_union(
            FunctionTransformer(copy), # it creates a copy of the data
            Normalizer(norm="max") # each row element is divided by the max value in the row.
        ),
        ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.25, min_samples_leaf=6, min_samples_split=4, n_estimators=100)
    )

    # 200? epochs, tpotConfigDic=None
    p2=make_pipeline(
        XGBClassifier(learning_rate=0.1, max_depth=10, min_child_weight=4, n_estimators=100, n_jobs=1, subsample=0.5, verbosity=0)    
    )

    # 100 epochs, tpotConfigDic=None
    p3=make_pipeline(
        StackingEstimator(
            estimator=ExtraTreesClassifier(bootstrap=True, criterion="gini", max_features=0.2, min_samples_leaf=19, min_samples_split=13, n_estimators=100)
        ),
        StackingEstimator(
            estimator=XGBClassifier(learning_rate=1.0, max_depth=6, min_child_weight=10, n_estimators=100, n_jobs=1, subsample=0.35000000000000003, verbosity=0)
        ),
        XGBClassifier(learning_rate=0.01, max_depth=6, min_child_weight=1, n_estimators=100, n_jobs=1, subsample=0.25, verbosity=0)
    )

    # 100 epochs, tpotConfigDict='TPOT light'
    # anche 1000 epochs, tpotConfigDict='TPOT light', stesso risultato di cui sopra
    p4=make_pipeline(
        StackingEstimator(
            estimator=DecisionTreeClassifier(criterion="gini", max_depth=10, min_samples_leaf=6, min_samples_split=3)
        ),
        BernoulliNB(alpha=0.1, fit_prior=False)
    )

    p5=make_pipeline(
        StackingEstimator(estimator=SGDClassifier(alpha=0.01, eta0=0.1, fit_intercept=True, l1_ratio=0.0, learning_rate="invscaling", loss="squared_hinge", penalty="elasticnet", power_t=10.0)),
        StackingEstimator(estimator=XGBClassifier(learning_rate=0.01, max_depth=1, min_child_weight=20, n_estimators=100, n_jobs=1, subsample=1.0, verbosity=0)),
        StackingEstimator(estimator=BernoulliNB(alpha=0.001, fit_prior=False)),
        StackingEstimator(estimator=SGDClassifier(alpha=0.01, eta0=1.0, fit_intercept=True, l1_ratio=1.0, learning_rate="constant", loss="hinge", penalty="elasticnet", power_t=10.0)),
        XGBClassifier(learning_rate=0.1, max_depth=6, min_child_weight=3, n_estimators=100, n_jobs=1, subsample=0.45, verbosity=0)
    )


    # 200? epochs, tpotConfigDic=None
    p101=make_pipeline(
        make_union(
            StackingEstimator(
                estimator=make_pipeline(
                    StackingEstimator(
                        estimator=GradientBoostingClassifier(learning_rate=0.5, max_depth=8, max_features=0.4, min_samples_leaf=4, min_samples_split=7, n_estimators=100, subsample=0.2)
                    ),
                    LinearSVC(C=0.1, dual=False, loss="squared_hinge", penalty="l1", tol=0.01)
                )
            ),
            FunctionTransformer(copy)
        ),
        StackingEstimator(
            estimator=SGDClassifier(alpha=0.0, eta0=1.0, fit_intercept=True, l1_ratio=0.75, learning_rate="invscaling",     loss="squared_hinge", penalty="elasticnet", power_t=0.1)
        ),
        ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.2, min_samples_leaf=5, min_samples_split=5, n_estimators=100)
    )

    # Maybe the FunctionTransformer is useless
    p101bis=make_pipeline(
        #make_union(
            StackingEstimator(
                estimator=make_pipeline(
                    StackingEstimator(
                        estimator=GradientBoostingClassifier(learning_rate=0.5, max_depth=8, max_features=0.4, min_samples_leaf=4, min_samples_split=7, n_estimators=100, subsample=0.2)
                    ),
                    LinearSVC(C=0.1, dual=False, loss="squared_hinge", penalty="l1", tol=0.01)
                )
            ),
            #FunctionTransformer(copy)
        #),
        StackingEstimator(
            estimator=SGDClassifier(alpha=0.0, eta0=1.0, fit_intercept=True, l1_ratio=0.75, learning_rate="invscaling",     loss="squared_hinge", penalty="elasticnet", power_t=0.1)
        ),
        ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.2, min_samples_leaf=5, min_samples_split=5, n_estimators=100)
    )



    # 100 epochs, tpotConfigDic=None
    p102=make_pipeline(
        make_union(
            StackingEstimator(estimator=LinearSVC(C=0.1, dual=False, loss="squared_hinge", penalty="l1", tol=0.01)),
            StackingEstimator(estimator=XGBClassifier(learning_rate=0.01, max_depth=10, min_child_weight=7, n_estimators=100, n_jobs=1, subsample=0.35000000000000003, verbosity=0))
        ),
        ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.35000000000000003, min_samples_leaf=5, min_samples_split=7, n_estimators=100)
    )

    # 100 epochs, tpotConfigDict='TPOT light'
    # Stessi risultati, ma anche con 1000 epoche
    p104=make_pipeline(
        make_union(
            FunctionTransformer(copy),
            FunctionTransformer(copy)
        ),
        Binarizer(threshold=0.4),
        DecisionTreeClassifier(criterion="gini", max_depth=8, min_samples_leaf=2, min_samples_split=17)
    )

    p104bis=make_pipeline(
        Binarizer(threshold=0.4),
        DecisionTreeClassifier(criterion="gini", max_depth=8, min_samples_leaf=2, min_samples_split=17)
    )

    p104ter=make_pipeline(
        DecisionTreeClassifier(criterion="gini", max_depth=8, min_samples_leaf=2, min_samples_split=17)
    )

    p105=make_pipeline(
        StackingEstimator(estimator=BernoulliNB(alpha=100.0, fit_prior=False)),
        StackingEstimator(estimator=LinearSVC(C=0.1, dual=True, loss="hinge", penalty="l2", tol=0.1)),
        StackingEstimator(estimator=SGDClassifier(alpha=0.01, eta0=0.1, fit_intercept=False, l1_ratio=0.25, learning_rate="invscaling", loss="modified_huber", penalty="elasticnet", power_t=100.0)),
        ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.55, min_samples_leaf=5, min_samples_split=20, n_estimators=100)
    )

    # This was created using the old dataset
    p106=make_pipeline(
        SelectPercentile(score_func=f_classif, percentile=83),
        RFE(estimator=ExtraTreesClassifier(criterion="gini", max_features=0.3, n_estimators=100), step=0.7500000000000001), # recursive feature elimination (RFE)
        StackingEstimator(estimator=LinearSVC(C=10.0, dual=False, loss="squared_hinge", penalty="l2", tol=0.001)),
        ExtraTreesClassifier(bootstrap=False, criterion="gini", max_features=0.2, min_samples_leaf=18, min_samples_split=9, n_estimators=100)
    )

    # See next comment
    p106bis=make_pipeline(
        #SelectPercentile(score_func=f_classif, percentile=83),
        RFE(estimator=ExtraTreesClassifier(criterion="gini", max_features=0.3, n_estimators=100), step=0.7500000000000001), # recursive feature elimination (RFE)
        StackingEstimator(estimator=LinearSVC(C=10.0, dual=False, loss="squared_hinge", penalty="l2", tol=0.001)),
        ExtraTreesClassifier(bootstrap=False, criterion="gini", max_features=0.2, min_samples_leaf=18, min_samples_split=9, n_estimators=100)
    )


    # This, like the previous was obtained by manually modifying the pipeline produced by tpot
    p106ter=make_pipeline(
        SelectPercentile(score_func=f_classif, percentile=83),
        #RFE(estimator=ExtraTreesClassifier(criterion="gini", max_features=0.3, n_estimators=100), step=0.7500000000000001), # recursive feature elimination (RFE)
        StackingEstimator(estimator=LinearSVC(C=10.0, dual=False, loss="squared_hinge", penalty="l2", tol=0.001)),
        ExtraTreesClassifier(bootstrap=False, criterion="gini", max_features=0.2, min_samples_leaf=18, min_samples_split=9, n_estimators=100)
    )


    jobDi={
           'j1':{'pipe':p1, 'datasetNickname':'early_warning_ml'},
           'j2':{'pipe':p2, 'datasetNickname':'early_warning_ml' },

           'j3':{'pipe':p3, 'datasetNickname':'early_warning_ml' },
           'j4':{'pipe':p4, 'datasetNickname':'early_warning_ml' },
           'j5':{'pipe':p5, 'datasetNickname':'early_warning_ml' },
           
           'j101':{'pipe':p101, 'datasetNickname':'early_warning_ml_rolling_window'},
           'j101bis':{'pipe':p101bis, 'datasetNickname':'early_warning_ml_rolling_window'},# p101bis
           'j102':{'pipe':p102, 'datasetNickname':'early_warning_ml_rolling_window'},
           'j102':{'pipe':p102, 'datasetNickname':'early_warning_ml_rolling_window'},
           'j104':{'pipe':p104, 'datasetNickname':'early_warning_ml_rolling_window'},
           'j104bis':{'pipe':p104bis, 'datasetNickname':'early_warning_ml_rolling_window'},
           'j104ter':{'pipe':p104ter, 'datasetNickname':'early_warning_ml_rolling_window'},
           'j105':{'pipe':p105, 'datasetNickname':'early_warning_ml_rolling_window' },
           'j106':{'pipe':p106, 'datasetNickname':'early_warning_ml_rolling_window' },
           'j106bis':{'pipe':p106bis, 'datasetNickname':'early_warning_ml_rolling_window' },
           'j106ter':{'pipe':p106ter, 'datasetNickname':'early_warning_ml_rolling_window' },


    }

    pdf = FPDF()

    pdfWidth = pdf.w 

    # Add main title
    
    
    f1AndPipeLi = [] 

    pipeNumber=1

    log('\n'+sep+'\n'+sep+'\n'+'# Several Pipelines Evaluation started\n'+sep)
    for jobName, jobInfo in jobDi.items():
        pipe = jobInfo['pipe'] 
        datasetNickName = jobInfo['datasetNickname']
        set_param_recursive(pipe.steps, 'random_state', random_state)
        report, f1Macro, figBuffer = evaluatePipeline(
            pipe, 
            datasetNickName,
        )

        pipeNickname = f'Pipe {pipeNumber}_{jobName}'

        pdf.add_page()
        pdf.set_font('Helvetica', 'b', 20)  
        pdf.ln(40)
        pdf.write(5, pipeNickname)
        pdf.ln(10)
        
        # Add informatio nabout a classifier in the report
        pdf.set_font('Helvetica', '', 14)
        pdf.set_text_color(r=128,g=128,b=128)
        
        pdf.write(4, f' Dataset: {datasetNickName}')
        pdf.ln(10)
        pdf.write(8, f' Pipe: {str(pipe)}')
        pdf.ln(10)
        pdf.write(4, report)
        
        pdf.ln(10) # Add line break

        # Save buffer to a temporary file-like object for FPDF

        temporarylocation=f"image/image{pipeNumber}.png"
        with open(temporarylocation,'wb') as out: ## Open temporary file as bytes
            out.write(figBuffer.read()) 
        #image_data = figBuffer.read()
        #image_stream = io.BytesIO(image_data)

        # FPDF requires a filename or file-like object with a name
        # Add a `name` attribute to satisfy FPDF if necessary
        #image_stream.name = 'plot.png'

        #figBuffer.name = 'plot.png'
        #pdf.image(figBuffer)
        #pdf.image(image_stream)
        pdf.image(temporarylocation, type='png', w=int(pdfWidth*.70))


        # Add line break
        pdf.ln(10)

        f1AndPipeLi.append( (f'{f1Macro:.2}', pipeNickname ) ) # str(pipe)
        pipeNumber+=1

    f1AndPipeLi.sort(reverse=True)

    # Inserting all the scores in the pdf
    allScoresDF = pd.DataFrame(data={'pipe':[el[1] for el in f1AndPipeLi], 'F1Macro':[el[0] for el in f1AndPipeLi]})

    # Table header?
    pdf.set_font("Helvetica", "B", 14)
    #pdf.set_char_spacing(10)
    pdf.cell(0, 10, "F1 Score Table", ln=True, align='C')
    pdf.ln(5)

    

    pdf.set_font("Helvetica", size=10)
    col_width = int(pdfWidth / len(allScoresDF.columns) *0.8) # Even column width
    row_height = 8

    # Header
    pdf.set_fill_color(200, 220, 255)
    for col_name in allScoresDF.columns:
        pdf.cell(col_width, row_height, col_name, border=1, fill=True, align='C')
    
    pdf.ln(row_height)

    # Data rows
    for _, row in allScoresDF.iterrows():
        for item in row:
            pdf.cell(col_width, row_height, str(item), border=1, align='C')
        pdf.ln(row_height)


    # Save the PDF
    pdfOutputFN="separate_pipes_evaluation_result.pdf"
    pdf.output(pdfOutputFN)
    print(f"Saved {pdfOutputFN}")




if __name__=="__main__":
    evaluateSeveralPipelines()

"""
# NonRollingDataset
def evaluateDatasetA1():
    # Additional Configuration

    tableName='cr03_ml' # 'cr03_ml_rolling' 'cr03_ml'
    rolling=False 

    covariates = baseCovariates + ['crisis0_1']

    dfb = readDataset(
        dbfn = dbfn,
        tableName=tableName
    )
        
    if 'index' in dfb.columns:
        dfb.drop(columns=['index'], inplace=True)

    # Checking that target variables and covariates are available
    for col in [targetVarName]+covariates:
        assert col in dfb.columns , f'Attribute *{col}* not found'
        
    #print(dfb.columns)

    trainSelectionMask = dfb.grp=='balanced_train'
    testSelectionMask = dfb.grp=='balanced_test'

    dfbTrain = dfb.loc[trainSelectionMask, covariates]
    dfbTest = dfb.loc[testSelectionMask, covariates]

    ybTrain = dfb.loc[trainSelectionMask, targetVarName]
    ybTest = dfb.loc[testSelectionMask, targetVarName]

    exported_pipeline = make_pipeline(
        make_union(
            FunctionTransformer(copy),
            Normalizer(norm="max")
        ),
        ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.25, min_samples_leaf=6, min_samples_split=4, n_estimators=100)
    )


    pipeb1 = make_pipeline(
        make_union(
            FunctionTransformer(copy),
            Normalizer(norm="max")
        ),
        ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.25, min_samples_leaf=6, min_samples_split=4, n_estimators=100)
    )

    # Fix random state for all the steps in the pipeline
    set_param_recursive(pipeb1.steps, 'random_state', random_state)

    evaluatePipeline(pipeb1, dfbTrain, dfbTest, ybTrain, ybTest, dbfn=dbfn, tableName=tableName, rolling=rolling)





#    covariates = baseCovariates + rollingAdditionalCovariates
#    tableName='cr03_ml_rolling'

"""
